### ISSUE TITLE
Construct 2 loader not visible when exporting for Ejecta?

### ISSUE THREAD

**Issue by abinop** [phoboslab/Ejecta#461]
Hey @AshleyScirra , @phoboslab , have a nice and prosperous  2015!

I have exported my Construct 2 game for iOS and I have indicated that I want a logo as a loader style, see http://cl.ly/image/1P0k2h2R441H. This works fine when I preview on the browser but when I export for Ejecta I never see the loader.

Do you need a test case for this?

Again, all the best for the new year.

**Comment by phoboslab** [comment]
I have no idea of any of the internals of Construct 2. If you can figure out what the loader does, how it attempts to display the image, and then isolate the issue, that would help a lot.

**Comment by AshleyScirra** [comment]
IIRC Construct 2 does not support displaying a loader on non-browser platforms, because it relies on DOM features (it involves overlaying a canvas2d context on top of the normal game context which could be either WebGL or canvas2d).

We dropped official support for Ejecta in r191 anyway, and we now recommend publishing with Cordova instead.
