### ISSUE TITLE
[REQUEST] need window.onload event

### ISSUE THREAD

**Issue by finscn** [phoboslab/Ejecta#501]
Some framework are Listening window.onload for initialization.

**Comment by phoboslab** [comment]
Ejecta provides a sensible, minimal _subset_ of the DOM APIs. DOMContentLoaded (https://developer.mozilla.org/en-US/docs/Web/Events/DOMContentLoaded) is the better way to do this and is already implemented in Ejecta.

That said, neither `onload` nor `DOMContentLoaded` makes much sense in Ejecta, because if your script executes, the "page" has been loaded anyway. There's no need to listen for any of these events.

**Comment by finscn** [comment]
How about unload ?

**Comment by phoboslab** [comment]
Mhh, I assumed `pagehide` would cover most things. What's your use-case?

**Comment by finscn** [comment]
If user  double press home when App is running  and  Swipe Up App Thumb to shutdown app, the pagehide not be fired

**Comment by phoboslab** [comment]
`pagehide` and `visibilitychange` is fired as soon as you double press Home.

What do you want to do when App shuts down? Couldn't this be also done when it enters the background? Afaik iOS is free to terminate paused apps without notice.
