### ISSUE TITLE
exc_bad_access when msaa is enabled

### ISSUE THREAD

**Issue by l4u** [phoboslab/Ejecta#509]
it works on the Simulator but crashes on iPhone 5.

```
#7	0x000aef7e in -[EJCanvasContext2DScreen present] at 
/Users/Leo/Ejecta/Source/Ejecta/EJCanvas/2D/EJCanvasContext2DScreen.m:116
```

```
		[glContext presentRenderbuffer:GL_RENDERBUFFER];
```

**Comment by phoboslab** [comment]
Still works for me if I enable it in the [example](https://github.com/phoboslab/Ejecta/blob/master/index.js) that comes with Ejecta (iPhone5S).

Can you confirm if the example works for you?

**Comment by l4u** [comment]
The example works for me.

I've created a failing case.

https://github.com/l4u/Ejecta-msaa/tree/msaa

Uncomment the 2 MSAA lines at `App/index.js`, the app crashes on the device. But it works on the simulator.

It might be related to fonts.

**Comment by phoboslab** [comment]
Thanks for the test-case. I couldn't reproduce a crash, but got a blank screen instead. The above commit fixed it for me. Can you please confirm on your device?

The problem only occurred in your test case, because the Chart.js library resizes the canvas multiple times and the recreation of the render buffer storage wasn't cleanly handled, when MSAA is enabled.

**Comment by l4u** [comment]
Thanks! It works.
