### ISSUE TITLE
EJBindingKeyInput can't support  "Multi-byte character sets" input method

### ISSUE THREAD

**Issue by finscn** [phoboslab/Ejecta#511]
like  Chinese / Japanese  input method.

When I change the  input method to  Chinese mode , I can't see and choose the Candidate words.

in Ejecta:
![2015-04-14 4 52 43](https://cloud.githubusercontent.com/assets/288367/7413475/d54bbb06-ef7e-11e4-8c1a-c1664417d458.png)

the normal  :  
![151126gsvhmpzt9c277c92](https://cloud.githubusercontent.com/assets/288367/7413556/608acbf8-ef7f-11e4-86d4-d82003594578.png)

I have already changed  the iOS to Chinese mode , and   add & open the Chinese Input Method

**Comment by phoboslab** [comment]
Apparently we'd need to support the UITextInput protocol, instead of UIKeyInput.
See: http://stackoverflow.com/questions/12016928/uikeyinput-is-not-called-when-using-japanese-keyboard - It's a quite a big protocol, also handling text selection, copy/paste etc.

I think it would be easier to create a UITextInput view that floats above the canvas. This way  you get all the text input methods for free, than to try and listen for keypresses.

**Comment by finscn** [comment]
I see.
 I will try to use  a  "webview + html page"  that floats above the Ejecta canvas .
You know I'm not a iOS developer , I'm a  web developer.

Thanks.
