### ISSUE TITLE
[Question] Has the effort to convert to ARC been abandoned?

### ISSUE THREAD

**Issue by sleepygarden** [phoboslab/Ejecta#536]
I my own codebase I've re-written a few of the EJ_BIND macros with bridging to allow me to use ARC binding classes. I'd be willing to dig into ARCifying/modernizing more of the repo unless it was tossed intentionally.

**Comment by phoboslab** [comment]
Not abandoned, but consciously decided against it for performance reasons. See https://github.com/phoboslab/Ejecta/pull/113#issuecomment-13350054 

I haven't done any investigating for ARC recently. Maybe the situation has changed or – likely – my ARC implementation was naive. But I still don't think we can do it without any performance loss.

**Comment by sleepygarden** [comment]
Alright, I might just push up my macros for using ARC when extending EJBinding

**Comment by appden** [comment]
I honestly think this is worth benchmarking again. ARC performance has improved a lot in the past couple years and can often beat MRC because of retain/release are direct runtime calls and it removes the need for autorelease in almost all cases. Just make sure to test with optimizations enabled. :smile:

**Comment by phoboslab** [comment]
Well, I'm not really interested in trying ARC again. Closing this issue, since nobody else seems to be interested in doing this either.

**Comment by sleepygarden** [comment]
I'm still willing to take a stab at it. what benchmarks are you using?
