### ISSUE TITLE
[REQUEST]  ejecta.openURL supports custom confirm title & button

### ISSUE THREAD

**Issue by finscn** [phoboslab/Ejecta#577]
When game is make for global and internationalization , Developers should set different confirm dialog in different areas.
I think if openURL API could  like this , it will be better:

```javascript
// current  version: 
ejecta.openURL(url) // no confirm
ejecta.openURL(url, message)  // just custom  body message 

// add a feature: 
ejecta.openURL(url,  options )   // custom all

options = {
   title:   "Will open a web page in Safari",
   message:  "Do you like it?"
   confirmButton:  "YES",
   cancelButton:  "NO",
}
```

**Comment by jmo84** [comment]
How about an option to skip the dialog altogether and just open the browser? If a user clicks a link that says"Official Site" or "My Site" they probably assume a browser is going to open.

**Comment by phoboslab** [comment]
@jmo84 calling `ejecta.openURL(url)` (without message param) will do exactly that.

Maybe the `message` param should be removed completely (and `ejecta.openURL()` aliased to `window.location`?). After all, the confirmation dialog could be done in JS if needed.

**Comment by finscn** [comment]
@phoboslab  ejecta.openURL could be aliased to window.open , not window.location , I think.

**Comment by finscn** [comment]
ejecta.openURL() is like window.open() , not  window. location , I think.

**Comment by jmo84** [comment]
@phoboslab thanks and that idea about window.location sounds good

**Comment by jmo84** [comment]
window.location = string;

should be supported, has anybody tested it?

**Comment by phoboslab** [comment]
`window.location.href` is currently just the string `"index"` (See [Ejecta.js](https://github.com/phoboslab/Ejecta/blob/master/Source/Ejecta/Ejecta.js#L189)). The whole thing doesn't exactly work like the Location object should ([spec](https://developer.mozilla.org/en-US/docs/Web/API/Window/location)).

I also think @finscn is right: `window.open()` would be a better candidate. Setting `window.location` to a URL would imply that the URL is opened in the current App, instead of in the browser.

**Comment by jmo84** [comment]
Yeah, window.open makes more sense since a browser window is going to open. Plus it'll be cross-platform unlike Ejecta.openURL. Forget what I said about window.location and make window.open work in Ejecta

**Comment by finscn** [comment]
```
window.open = function(url, confirm) {
	if (arguments.length > 1) {
		ejecta.openURL(url, confirm);
	} else {
		ejecta.openURL(url);
	}
};
```

Is this OK ?

**Comment by amadeus** [comment]
I would say no confirm parameter. That's something the dev can easily create using window.confirm() or whatever.

**Comment by jmo84** [comment]
Agree window open should just open a browser tab or window. I have an
overriding wrapper function just like the code above but I wrap mine in

if (type of ejecta != "undefined")

... so that window.open works normally in browsers. It'd be great if
window.open worked the same as ejecta.openURL in Ejecta so I wouldn't have
to add a wrapper for ejecta.openURL

What I think would be better for UX would be the ability to show a ui web
view, but that's a another request that I think is already closed as out of
scope.

Maybe a compromise could be no web view but the ability to load html
documents that include on script tags, like impact or phaser

My ejecta app is loading great but more options might help somebody else

**Comment by phoboslab** [comment]
`window.open(url)` now works as expected.
