### ISSUE TITLE
[BUG] about draw path in iOS 8  device

### ISSUE THREAD

**Issue by finscn** [phoboslab/Ejecta#579]
This is a complex issue , and you know , my english is very weak, so I will try my best to explain it.

It has happened  only in iOS 8 device  (not simulator, not iOS 9 , not browser ).

My case is a prototype , no image, all graphics create with  fill/stroke path & fillRect/strokeRect.

In iOS 8 device, when draw(stroke or fill) some paths , the screen canvas  freezes, not  refresh again.
But game doesn't suspend ,  the console & sound & input handler  work well.

The codes  of game  too many too complex to send.

 in recent update, the Ejecta if do something not supports iOS 8 ?

**Comment by finscn** [comment]
I  write a test case ,  index.js  

```javascript

// init default screen canvas & context
var width = window.innerWidth;
var height = window.innerHeight;

var canvas = document.getElementById('canvas');
canvas.width = width * window.devicePixelRatio;
canvas.height = height * window.devicePixelRatio;
canvas.style.width = width + "px";
canvas.style.height = height + "px";
var context = canvas.getContext("2d");


setTimeout(startTest, 100);

function startTest() {

    // resize screen canvas
    canvas.width = 960;
    canvas.height = 541;
    canvas.style.width = 568 + "px";
    canvas.style.height = 320 + "px";

    setInterval(function() {
        context.fillStyle = "rgba(220,220,220,1)";
        context.fillRect(0, 0, canvas.width, canvas.height);

        context.fillStyle = "black";
        context.fillText(Date.now() + "", 50, 100);

        context.strokeStyle = "rgba(0,0,0,0.5)";
        context.beginPath();
        context.arc(100, 100, 100, 0, Math.PI * 2);
        context.closePath();
        context.stroke();

    }, 33)
}

```

**Comment by finscn** [comment]
I found after resize screen canvas again,   everything will be wrong in iOS device .

The old version (before Nov 4, 2015) is OK.

**Comment by finscn** [comment]
@phoboslab  , could you reproduce this bug ?

**Comment by phoboslab** [comment]
I don't have an iOS8 device anymore.

I believe earlier iOS versions might not support a `contentScale` that's not an Integer value (i.e. `1`, `2` or `3`). In your example, you end up with a contentScale of 1.69. (960/568), which may not be supported by the OS.

Notice how earlier Ejecta versions [didn't allow a non-Integer contentScale](https://github.com/phoboslab/Ejecta/commit/dcda604867eccfe6f97acbc13a8b8a1f9428be9a#diff-7b9dac546e305c004b56c38e48d7f442L57). It was either set to `1` or to `UIScreen.mainScreen.scale`.

Similarly, in earlier Ejecta versions, the [WebGL context produced a warning with a non-Integer contentScale](https://github.com/phoboslab/Ejecta/commit/40307624df59fc07ef718678f3ebc00b60f4e44d). Also see #441.


I can't find any documentation from Apple if a non-Integer contentScale is supported by iOS or not. It seems to work on iOS9. Since you say this only happens in certain cases - when drawing shapes - it may be related to the stencil buffer in OpenGL. I wasn't able to reproduce #441 for WebGL back then with my test cases either; maybe because non of those need a stencil buffer.

**Comment by phoboslab** [comment]
Upon closer investigation: this may indeed be an issue with the stencil buffer. It may be created in the wrong size due to rounding errors. `[glContext renderbufferStorage]` seems to always round *down* from the `canvas.style.width / contentScale` calculation, resulting in a mismatch between the requested canvas size and the created render buffer size.

Can you add the following code at [line 87 in EJCanvasContext2DScreen.m](https://github.com/phoboslab/Ejecta/blob/master/Source/Ejecta/EJCanvas/2D/EJCanvasContext2DScreen.m#L87) and see if it makes a difference:

```objc
GLint rbWidth, rbHeight;
glGetRenderbufferParameteriv(GL_RENDERBUFFER, GL_RENDERBUFFER_WIDTH, &rbWidth);
glGetRenderbufferParameteriv(GL_RENDERBUFFER, GL_RENDERBUFFER_HEIGHT, &rbHeight);
NSLog(@"Requested Size: %dx%d, Real Renderbuffer Size: %dx%d", bufferWidth, bufferHeight, rbWidth, rbHeight);

bufferWidth = rbWidth;
bufferHeight = rbHeight;
```

**Comment by finscn** [comment]
Create! add those codes , everything is ok .
I think add a code for check iOS version is better:
```
    if(EJECTA_SYSTEM_VERSION_LESS_THAN(@"9.0")){
        GLint rbWidth, rbHeight;
        glGetRenderbufferParameteriv(GL_RENDERBUFFER, GL_RENDERBUFFER_WIDTH, &rbWidth);
        glGetRenderbufferParameteriv(GL_RENDERBUFFER, GL_RENDERBUFFER_HEIGHT, &rbHeight);
        NSLog(@"Requested Size: %dx%d, Real Renderbuffer Size: %dx%d", bufferWidth, bufferHeight, rbWidth, rbHeight);
        
        bufferWidth = rbWidth;
        bufferHeight = rbHeight;
    }
```

**Comment by phoboslab** [comment]
Problem is, changing the `bufferWidth` and `bufferHeight` to a different one than the user requested would be very confusing. If you think your canvas' internal res 960, but it's really 958, you may be drawing at the wrong positions, getting pixel data out of bounds and have all kinds of other problems.

I think it's better to resize the `canvas.style` if needed - round it up so `[glContext renderbufferStorage ...]` will create the render buffer in the requested size. I'm not really sure how to do that, though; I don't know how `renderbufferStorage` calculates the buffer size.
