### ISSUE TITLE
Black screen, no error on device for globalCompositeOperation "destination-in" 

### ISSUE THREAD

**Issue by idibidiart** [phoboslab/Ejecta#589]
When I set Canvas ctx.globalCompositeOperation to "destination-in" I get a black screen on iOS

only working blend modes are:

lighter, source-over, xor, source-out, copy, and destination-over 

Is this a bug or could it be that my canvas routines produce no visible output with the other settings for globalCompositeOperation?

**Comment by idibidiart** [comment]
only working blend modes are:

lighter, source-over and destination-over

**Comment by phoboslab** [comment]
The situation is kinda difficult. I believe `destination-in` and `source-in` work correctly when drawing images, but will fail for shapes. I don't have much interest in fixing it currently, because of the (imho) very limited use-cases and huge added complexity. See: https://github.com/phoboslab/Ejecta/pull/202

What exactly are you trying to do? Maybe there's a workaround.

**Comment by idibidiart** [comment]
Actually, turns out that for the example I was working with, both destination-in and source-in give me a black/blank screen in the browser, too, so while there may be an issue with those modes in Ejecta, my use case is consistent across browser and Ejecta.
