### ISSUE TITLE
Using socket.io + Ejecta

### ISSUE THREAD

**Issue by iam-peekay** [phoboslab/Ejecta#609]
I am using Ejecta for a simple app that listens to a socket.io server and draws the images coming from server to canvas on the client. 

I am trying to include the standalone build of socket.io.js source by appending the script to the body:
```javascript
var script = document.createElement('script');
script.src = 'socket.io.js'
document.body.appendChild(script);
console.log('io', window.io);
```
which exposes "io" global variable on window. But I keep getting "JS LOG: io undefined" error. 

Is there anything wrong with this approach of importing an external library?

**Comment by iam-peekay** [comment]
I figured out that we can use eject.include:
```javascript
ejecta.include('socket.io.js');
var socket = io.connect('http://localhost:8000');
socket.on('connect', function() {
          console.log('connection on client');
          });
```

However, I get an error saying:
 "2016-02-08 13:02:51.523 Ejecta[10985:553076] Error: **The script http://localhost:8000/socket.io/?EIO=3&transport=polling&j=0&t=LB2iR9k&b64=1 does not exist or appears to be empty.**"

Would love any help!

**Comment by phoboslab** [comment]
Responding to your email, so that it's all in one place. I hope that's ok.

> The other weird thing that is happening is that it is getting run twice. So the first error I showed above is from Ejecta and the second one from Socket.io that says "TypeError: undefined is not an object (evaluating 'this.script.parentNode.removeChild') at line 1065 in socket.io-client/socket.io.js"

> So it's running a second time and trying to do json poll for some reason. Meaning, the logic for detecting that xhr is supported is not passing. Perhaps its related to CORS? It's weird that the xhr to poll fails AND it also tries jsonp. Would you happen to know what might be causing this?

Ejecta doesn't support the `parentNode` property on HTMLElements (such as the Script Tag(?) SocketIO is trying to remove). Remember, the DOM in Ejecta is only a very thin "fake" layer, supporting very few basic functions. And while Ejecta supports XMLHttpRequest and WebSockets - both very close to the spec - it seems SocketIO relies heavily on the DOM.

The other error (`The script http://localhost:8000/socket.io/?EIO=3&transport=polling&j=0&t=LB2iR9k&b64=1 does not exist or appears to be empty.`) stems from the fact, that Ejecta can't load Script files from HTTP. It only supports loading Scripts from local files. I don't know why SocketIO adds yet another Script element with that HTTP source to the DOM. This would be workaroundable with an XMLHttpRequest and good old `eval()`, though.

Someone familiar with SocketIO can probably tell you more about what's going on and what the lib is trying to achieve. So I suggest you open an issue in the SocketIO repo as well.

That said, I don't think SocketIO is a good fit for Ejecta. SocketIO's main purpose is to provide backwards compatibility for shitty browers, dragging along a lot of baggage and assumptions that do not hold for Ejecta.

**Comment by iam-peekay** [comment]
@phoboslab thank you. I've been looking into this a little more. Here's what I learned:

With the first error (on the script not existing), socket.io does in fact use an XMLHttpRequest to load the uri. However, I'm seeing that your implementation of XMLHttpRequest does not have the 'withCredentials' property, so that is probably why it's failing in the below check that socket.io has: 

```javascript
try {
  module.exports = typeof XMLHttpRequest !== 'undefined' &&
    'withCredentials' in new XMLHttpRequest();
} catch (err) {
  // if XMLHttp support is disabled in IE then it will throw
  // when trying to create
  module.exports = false;
}
```
so module.exports ends up as **_false_**. If I remove the  'withCredentials' check such that it's ```module.exports = typeof XMLHttpRequest !== 'undefined'```, then I am receiving socket events from my socket.io server.

I'll have to check if this will cause bugs anywhere else, but just wanted to let you know that removing the withCredentials check made it work. 

Just for my own understanding, can I ask why you've chosen to exclude this from your spec of XMLHttpRequest?

**Comment by phoboslab** [comment]
Interesting! According to the [docs](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials), `withCredentials` only indicates whether CORS requests (those that go to a different origin/domain than the hosting script) should include credentials.  Ejecta doesn't have the `withCredentials` property because it doesn't care about CORS - i.e. it always behaves as if the request goes to the same origin as the hosting script.

For cases like these, it would probably still make sense to support this property, even if it does nothing. In the meantime, you could also just set this property on XMLHttpRequest in your scripts yourself, instead of modifying SocketIO.
```js
XMLHttpRequest.prototype.withCredentials = false;
```

**Comment by iam-peekay** [comment]
@phoboslab thanks again for looking into this issue with me! I'll close the issue. :+1:
