### ISSUE TITLE
How the hell are we supposed to use this?

### ISSUE THREAD

**Issue by McFarts** [phoboslab/Ejecta#619]
Where is the installation guide? Do we just compile it from source with VS or what?

**Comment by McFarts** [comment]
Btw, I don't use IOS. Why is this specifically for ISO when all OS's can take advantage? Seems very silly.

**Comment by Swinkid** [comment]
On the main page it says "More info & Documentation: http://impactjs.com/ejecta"

Also, its OSX/IOS only because you need to be able to run the iOS emulator. That's how the author has decided it to be, so it's not really that silly at all. It's a library aimed at iOS.

if you want something cross platform, consider buying impact on the homepage of the above link.

**Comment by phoboslab** [comment]
I'm so sorry to have failed you. Maybe if I was a better programmer, I could create a less-silly framework :(

**Comment by McFarts** [comment]
I already have bought impact, but I want to use ejecta on windows, not only for IOS. @phoboslab  I didn't mean it like that, I mean why not have the custom bindings work outside of just mobile devices? The performance would be better wouldn't it?

**Comment by phoboslab** [comment]
Well, yes, the performance would be better. It's just a whole lot of work to make Ejecta support Windows, Android, (to a lesser extent) OSX or any other platform.

I made this for iOS, because iOS needs it the most. On Desktop systems, Chrome should be fast enough and there are various way to package your App/Game with a Chromium Wrapper. On Android there are wrappers like Crosswalk that do a good job an perform reasonably well. On iOS there was no alternative to Safari.

**Comment by McFarts** [comment]
@phoboslab  I see, the reason is because I was discussing some WebGL stuff yesterday here: https://github.com/pixijs/pixi.js/issues/2366#issuecomment-187432144

And he mentioned how ejecta is the layer that connects OGL API w/ Javascript directly. Without the needing of the browser (Why Ejecta was born) to boost performance.

I'm just curious because you're right, I can package my app using chromium, and have access to v8, dom, css and everything and stick that baby inside Electron / NW.js. That's what I am doing now, but I wanted to stick it inside something like Ejecta instead and see if there would be a performance difference.  I guess it's already possible, but only for IOS and mobile devices. Which I didn't mean to come off as a ad-hominem attack against you I apologize for that. I meant it just seems silly why it only supports IOS because of the performance gains can be utilized outside of IOS.  But I guess it boils down if it's something that is needed and I guess I'm the only one requesting it.. So it's probably not needed. I'm just trying to find a way to get every single ounce of performance I can for my game. (Which will not be available on a mobile device).

**Comment by phoboslab** [comment]
@McFarts I'm glad you replied again and came of reasonably now. You tone in your initial posts just threw me off.

I believe, if the performance increase would be worth it on Desktop browsers, depends on your game/app to a large degree. Desktops are already a magnitude faster than mobile and if you're using WebGL (not Canvas2D), the performance increase to a native wrapper like Ejecta will be slim.

The thing is, the rendering portion of Ejecta (the Canvas2D and WebGL bindings) are only a small part of the whole project and probably the ones most easily portable. The much larger effort would be to bring all the other APIs over to other platforms, because those are not backed by a cross platform library (OpenGL), but by native iOS stuff: XMLHttpRequest, WebSockets, Gamepad, Sound and a bunch of others mainly use functions only available on iOS.

Still, a "cross-platform Ejecta" would be neat. I just don't see this happening anytime soon without any financial backing. I'm not aware of any other efforts like Ejecta or the closed source CocoonJS that run on Desktop systems.

**Comment by McFarts** [comment]
I see now @phoboslab. Thank you for the insights and future plans. 

> WebGL (not Canvas2D), the performance increase to a native wrapper like Ejecta will be slim.

I think this is what I needed to hear to shut me up about all this :) I guess the time / development to performance ratio just wouldn't be worth it for the desktop environment.


I have a special place in my heart for JS and think it's very underrated and it's so powerful now with all the libraries. I am just trying to remove the systematic stigma of "The only way to make a successful game is to learn C++!". Which is why I have these strong emotions about performance. Because everyone always bashes how Javascript is the bottleneck when used with graphics. Which is true to an extent, but for 2d games... it's negligible I believe. Impact will play a  vital role in the future of Javascript game development and I just want it to have the best performance possible that's all.

 I hope you continue to be the front-runner defending Javascript and make Javascript based games great again with Impact 2.0 / your future plans. It's definitely needed in the community, Javascript is under siege.
