### ISSUE TITLE
Why not use <JSExport> protocol to bind API?

### ISSUE THREAD

**Issue by hdu-rtt** [phoboslab/Ejecta#673]
Why not use <JSExport> protocol to bind API  instead use `createJSObjectWithContext` method?  I think use <JSExport> protocol is more convenient?

**Comment by hdu-rtt** [comment]
@phoboslab Thanks for answering!

**Comment by phoboslab** [comment]
Two reasons: 

1) When I started to work on Ejecta, JavaScriptCore only had the C-API. The ObjC-API (i.e. JSExport) was added later.

2) The ObjC-API is extremely slow compared to the C-API. This matters when you have to deal with a lot of function calls and convert a lot of JSValues to native types - i.e. the typical uses for WebGL and Canvas.

**Comment by hdu-rtt** [comment]
Sorry, I still don't quite understand.
1. Memory
In Ejecta, one "Native class" create one "JSObject" In JSContext that seems like cost more memory.  
JSExport just wrapper "Native class". from the document "When an Objective-C object is exported to JavaScript, a JavaScript wrapper object is created."
2. FuntionCall
In Ejecta, call function through `callAsFunction = (JSObjectCallAsFunctionCallback)[class performSelector:call];` 
Ejecta also use `objc_msgSend`, why fast compared to the `JSExport` call?

**Comment by phoboslab** [comment]
JSExport creates JSObjects as well (see: [JSWrapperMap.mm](https://github.com/phoboslab/JavaScriptCore-iOS/blob/master/JavaScriptCore/API/JSWrapperMap.mm#L431)). How else would JS know about the native class?

Likewise, JSExport creates a `ObjCCallbackFunction` for each method of the class. Just follow the trail through [objCCallbackFunctionForMethod](https://github.com/phoboslab/JavaScriptCore-iOS/blob/master/JavaScriptCore/API/JSWrapperMap.mm#L214) and all of [ObjCCallbackFunction.mm](https://github.com/phoboslab/JavaScriptCore-iOS/blob/master/JavaScriptCore/API/ObjCCallbackFunction.mm) to see how much indirection there is.

There is no magic in JSExport - it has to go through the same steps as Ejecta's implementation and more. Because it's more general and more convenient to use, it has to do a lot more work. Granted, for most uses of JSC in Apps this overhead is totally fine, but for Ejecta it wasn't.

**Comment by hdu-rtt** [comment]
I got it. Thank you very much! Ejecta is a very awesome library.  :)
